export const PrefsFields = {
    HISTORY_SIZE           : 'history-size',
    PREVIEW_SIZE           : 'preview-size',
    CACHE_FILE_SIZE        : 'cache-size',
    CACHE_ONLY_FAVORITE    : 'cache-only-favorites',
    DELETE                 : 'enable-deletion',
    NOTIFY_ON_COPY         : 'notify-on-copy',
    CONFIRM_ON_CLEAR       : 'confirm-clear',
    MOVE_ITEM_FIRST        : 'move-item-first',
    ENABLE_KEYBINDING      : 'enable-keybindings',
    TOPBAR_PREVIEW_SIZE    : 'topbar-preview-size',
    TOPBAR_DISPLAY_MODE_ID : 'display-mode',
    DISABLE_DOWN_ARROW     : 'disable-down-arrow',
    STRIP_TEXT             : 'strip-text',
    KEEP_SELECTED_ON_CLEAR : 'keep-selected-on-clear',
    PASTE_BUTTON           : 'paste-button',
    PINNED_ON_BOTTOM       : 'pinned-on-bottom',
    BINDING_TOGGLE_MENU    : 'toggle-menu',
    BINDING_CLEAR_HISTORY  : 'clear-history',
    BINDING_PREV_ENTRY     : 'prev-entry',
    BINDING_NEXT_ENTRY     : 'next-entry',
    BINDING_PRIVATE_MODE   : 'private-mode-binding',
    CLEAR_ON_BOOT          : 'clear-on-boot',
    PASTE_ON_SELECT        : 'paste-on-select',
    CACHE_IMAGES           : 'cache-images',
};
